name: main

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy:
        description: "Deploy? (y/sha/N)"
        required: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PUBLISH_CHANNEL: ${{ github.event.inputs.deploy == 'y' && 'latest' || 'sha' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
      - run: yarn install --frozen-lockfile
      - run: |
          yarn concurrently \
            --names "lint,lint:ts,test,build" \
            "yarn lint" \
            "yarn lint:ts" \
            "yarn test" \
            "yarn build"
      - run: yarn test:e2e
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deploy == 'y' || github.event.inputs.deploy == 'sha' }}
    concurrency:
      group: deploy
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Publish
        run: |
          npm publish \
            --access public \
            --tag ${{ github.event.inputs.deploy == 'y' && 'latest' || 'sha' }}
        working-directory: dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Tag
        if: ${{ github.event.inputs.deploy == 'y' }}
        run: git tag v$(cat dist/package.json | grep '"version"' | awk '{print$2}' | sed 's/[",]//g')
      - uses: ad-m/github-push-action@master
        if: ${{ github.event.inputs.deploy == 'y' }}
        with:
          tags: true
